# -*- coding: utf-8 -*-
"""Iris .csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GlCWAeHx8Z9TlOi9MXh-yXpKGBeY5gCf
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("/content/Iris.csv")
df

df.boxplot(figsize=(10,8))

df.plot(kind = "density", figsize=(15,5))

#plot histogram  on iris feature
df.hist(bins=15,figsize=(10,10))
plt.show

#pair plot
sns.pairplot(df, hue="Species")
plt.show()

#Barplot
sns.countplot(data=df, x="Species")
plt.title("Count of Each Species")
plt.show()

#1find how many flowers belong to each species
print(df["Species"].value_counts())

#2 what is the distribution of petal length
import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(data=df, x="PetalLengthCm", bins=10, kde=True)

plt.title("Distribution of Petal Length")
plt.xlabel("Petal Length (cm)")
plt.ylabel("Frequency")

plt.show()

# 3 what is the relationship between petal length and petal  width
import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(
    data=df,
    x="PetalLengthCm",
    y="PetalWidthCm",
    hue="Species"
)

plt.title("Relationship between Petal Length and Petal Width")
plt.xlabel("Petal Length (cm)")
plt.ylabel("Petal Width (cm)")
plt.show()

# 4 compare petal length between species
import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(data=df, x="Species", y="PetalLengthCm")

plt.title("Comparison of Petal Length Between Species")
plt.xlabel("Species")
plt.ylabel("Petal Length (cm)")

plt.show()